apiVersion: v1
kind: ServiceAccount
metadata:
  name: sev-webhook
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  name: sev-webhook
  namespace: kube-system
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: sev-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sev-webhook
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sev-webhook
  template:
    metadata:
      labels:
        app: sev-webhook
    spec:
      serviceAccountName: sev-webhook
      containers:
      - name: webhook
        image: seudockerhub/sev-webhook:latest
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/webhook/certs
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: sev-webhook-certs